
create_setupfile <- function(file, sim_options){
  
  header <- c("# Forceps setup file", paste0('# Generated on Rstudio by user ', Sys.info()["user"], ", on the ", Sys.Date()), "")
  write(header, file)
  
  lines_to_write <- c(paste("siteFileName","=", sim_options$siteFileName, sep=" "), 
                      "",
                      paste("speciesFileName","=", sim_options$speciesFileName, sep=" "),
                      paste("defaultClimateFileName","=", sim_options$defaultClimateFileName, sep=" "), 
                      "",
                      paste("bareGround","=", sim_options$bareGround, sep=" "),
                      paste("bareGroundPatchN","=", sim_options$bareGroundPatchN, sep=" "),
                      paste("bareGroundPatchArea","=", sim_options$bareGroundPatchArea, sep=" "),
                      "",
                      paste("inventory","=", sim_options$inventory, sep=" "),
                      paste("inventoryFileName","=", sim_options$inventoryFileName, sep=" "),
                      "",
                      paste("adaptiveMode","=", sim_options$adaptative_options$Mode, sep=" "),
                      paste("adaptiveInputCompleteExport","=", sim_options$adaptative_options$InputCompleteExport, sep=" "),
                      paste("adaptiveVarianceLevel","=", sim_options$adaptative_options$VarianceLevel, sep=" "),
                      paste("adaptiveTradeOffOption","=", sim_options$adaptative_options$TradeOffOption, sep=" "),
                      paste("adaptiveInventoryPatchN","=", sim_options$adaptative_options$InventoryPatchN, sep=" "),
                      paste("adaptiveInventoryPatchArea","=", sim_options$adaptative_options$InventoryPatchArea, sep=" "),
                      paste("adaptiveInitial_laSd","=", sim_options$adaptative_options$Initial_laSd, sep=" "),
                      paste("adaptiveInitial_drtolSd","=", sim_options$adaptative_options$Initial_drtolSd, sep=" "),
                      paste("adaptiveInitial_gSd","=", sim_options$adaptative_options$Initial_gSd, sep=" "),
                      paste("adaptiveExtraVariance_drtol","=", sim_options$adaptative_options$ExtraVariance_drtol, sep=" "),
                      paste("adaptiveExtraVariance_g","=", sim_options$adaptative_options$ExtraVariance_g, sep=" "),
                      paste("adaptiveTreeReproductionWeight","=", sim_options$adaptative_options$TreeReproductionWeight, sep=" "),
                      "",
                      paste("initDate","=", sim_options$initDate, sep=" "),
                      paste("randomSeed","=", sim_options$randomSeed, sep=" "),
                      "",
                      paste("distProba","=", sim_options$distProba, sep=" "),
                      "",
                      paste("deathProbaCoef","=", sim_options$deathProbaCoef, sep=" "),
                      "",
                      paste("slowGrowthProba","=", sim_options$slowGrowthProba, sep=" "),
                      "",
                      paste("slowGrowthTime","=", sim_options$slowGrowthTime, sep=" "),
                      "",
                      paste("potentialSpeciesList","=", sim_options$potentialSpeciesList, sep=" "),
                      "",
                      "# If true, trees get a real crown length",
                      paste("crownLengthOption","=", sim_options$crownLengthOption, sep=" "),
                      paste("crownLengthImpactOnGrowth","=", sim_options$crownLengthImpactOnGrowth, sep=" "),
                      "",
                      "# Regeneration: one option out of these 3 must be selected",
                      paste("regenerationMaxTreesPerPatchOption","=", sim_options$regeneration_options$MaxTreesPerPatchOption, sep=" "),
                      paste("regenerationMaxTreesPerPatchNumber","=", sim_options$regeneration_options$MaxTreesPerPatchNumber, sep=" "),
                      paste("regenerationMaxTreesPerPatchWithNTries","=", sim_options$regeneration_options$MaxTreesPerPatchWithNTries, sep=" "),
                      paste("regenerationMaxTreesPerPatchNTries","=", sim_options$regeneration_options$MaxTreesPerPatchNTries, sep=" "),
                      paste("regenerationSeedlingsPerPatchOption","=", sim_options$regeneration_options$SeedlingsPerPatchOption, sep=" "),
                      paste("regenerationSeedlingsPerPatchNumber","=", sim_options$regeneration_options$SeedlingsPerPatchNumber, sep=" "),
                      paste("regenerationForclimLike","=", sim_options$regeneration_options$ForclimLike, sep=" "),
                      "",
                      "# Regeneration: additional options",
                      paste("regenerationActualSpeciesOnly","=", sim_options$regeneration_options$ActualSpeciesOnly, sep=" "),
                      paste("regenerationActualSpeciesOnlyAtPatchLevel","=", sim_options$regeneration_options$ActualSpeciesOnlyAtPatchLevel, sep=" "),
                      paste("regenerationConstraint","=", sim_options$regeneration_options$Constraint, sep=" "),
                      paste("regenerationActualSpeciesOnlyAbundance","=", sim_options$regeneration_options$ActualSpeciesOnlyAbundance, sep=" "),
                      "",
                      paste("establishmentProbabilityCoef","=", sim_options$establishmentProbabilityCoef, sep=" "),
                      "",
                      paste("ppMothActivated","=", sim_options$ppMoth_options$Activated, sep=" "),
                      paste("ppMothRegionalPercentageOfInfestedTreesOption","=", sim_options$ppMoth_options$RegionalPercentageOfInfestedTreesOption, sep=" "),
                      paste("ppMothRegionalPercentageOfInfestedTrees","=", sim_options$ppMoth_options$RegionalPercentageOfInfestedTrees, sep=" "),
                      "",
                      paste("variability","=", sim_options$variability, sep=" "),
                      paste("variabilityFileName","=", sim_options$variabilityFileName, sep=" "),
                      "",
                      paste("climaticFitness","=", sim_options$climaticFitness, sep=" "),
                      paste("fitnessImpactsGrowth","=", sim_options$fitnessImpactsGrowth, sep=" "),
                      "",
                      paste("management","=", sim_options$management, sep=" "),
                      paste("managementFileName","=", sim_options$managementFileName, sep=" "),
                      "",
                      paste("droughtStressOption","=", sim_options$droughtStressOption, sep=" ")
                      )
  
  write(lines_to_write , file, append = TRUE)
  
}
