# Setup script

library(dplyr)
library(ggplot2)
library(cowplot)
library(extrafont)
library(zoo)
library(data.table)
library(ecospat)
library(dplyr)
library(precrec)
library(ggplot2)
library(modEvA)
library(terra)
library(minpack.lm)
library(nlraa)
library(propagate)
library(ordbetareg)
library(grid)
library(ggnewscale)
library(tidyterra)