# R packages
library(raster)
library(terra)
library(data.table)
library(DescTools)
library("doFuture")
registerDoFuture()
library(future.apply)
library(dplyr)
library(lubridate)
library(zoo)
library(progressr)

# Custom functions
source(file.path(wd, "functions", "years_functions.R"))
source(file.path(wd, "functions", "gwgen.R"))
source(file.path(wd, "functions", "gwgen_in_parallel.R"))
source(file.path(wd, "functions", "write_gwgen_csv.R"))
source(file.path(wd, "functions", "write_gwgen_csv_2rasters.R"))
source(file.path(wd, "functions", "leap_year.R"))
source(file.path(wd, "functions", "interpolate_cs_radiation.R"))
source(file.path(wd, "functions", "compute_glo_radiation_from_cs.R"))
source(file.path(wd, "functions", "format_phenofit.R"))
source(file.path(wd, "functions", "phenofit_file.R"))
source(file.path(wd, "functions", "calculate_perh.R"))
source(file.path(wd, "functions", "compute_toa_radiation.R"))
source(file.path(wd, "functions", "compute_glo_radiation_from_toa.R"))
source(file.path(wd, "functions", "load_altitude.R"))
