###############################################################
# Script to perform a Variogram Analysis of Response Surfaces #
###############################################################

# use the STAR_out.smp file generated by VARS Toolbox (MatLab)


# Setup
wd <- "C:/Users/vandermeersch/Documents/CEFE/phd/forceeps"
source(file.path(wd, "sensitivity_analysis", "setup.R"))
source(file.path(wd, "functions", "read_auc.R"))


# Read parameter matrix
VARS_dir <- "C:/Users/vandermeersch/Documents/CEFE/phd/global_sensitivity_analysis/razavi_et_al/2019_11_16_VARS-Tool-v2.1/VARS"
parameter_matrix_file <- file.path(VARS_dir, "forceeps_out_3", "STAR_out.smp")
parameter_matrix <- fread(parameter_matrix_file, header=F)


# Load presence/absence (to compute AUC)
load("D:/species/processed/fagus_sylvatica/fagussylvatica_occ_rs.Rdata")
species_occurrence <- as.data.frame(fagussylvatica_occ_rs, xy=T)
names(species_occurrence)[1:2] <- c("lon", "lat")
species_occurrence$lat <- round(species_occurrence$lat, 1)
species_occurrence$lon <- round(species_occurrence$lon, 1)
species_occurrence <- inner_join(alt_subset, species_occurrence, by = c("lat", "lon"))
species_occurrence$pres <- 0
species_occurrence[species_occurrence$nb_src>0, "pres"] <- 1
Yobs <- species_occurrence
obs <- as.factor(Yobs$pres)


# Run model
var <- "adultTreeBasalArea" # variable of interest
output_path <- file.path(wd, "sensitivity_analysis", "vars_model_simulations_3") 
parameters_fixed <- c("kType", "kNTol", "kBrow", "kLQ", "kImmT", "ageMaturityForReproduction")
system.time(model_output <- run_model_from_mat(parameter_matrix, ncores = 20))

# 84194s to run 10900 simulations


# Read AUC
pattern <- "\\.siteproductivity.txt$"
cnames <- c("date", "patchId", "speciesId", "speciesShortName", "adultProdBasalArea", "adultProdBiomass", "adultTreeBasalArea", "adultTreeBiomass", 
            "deadBasalArea", "deadBiomass", "saplingBasalArea", "saplingBiomass", "adultTreeNumber", "deadNumber", "saplingNumber", "droughtIndexAnnual",
            "droughtIndexSeasonal")
nyears <- commandfile_options$numberOfYears
nsites <- length(commandfile_options$grid)

handlers(global = TRUE)
auc_output <- c()
nind <- nrow(parameter_matrix)
npack <- 100
inds <- split(1:nind, cut(seq_along(1:nind), npack, labels = FALSE))
system.time(for(i in 1:npack){
  auc_i <- read_auc(inds[[i]], ncores = 40)
  auc_output <- c(auc_output, auc_i)
})

# 21438s to read 9100 simulations * 990 sites... (6 hours)
# 21421s to read 10000 simulations * 990 sites 
# 21080s to read 10900 simulations * 990 sites

save_file <- file.path(VARS_dir, "forceeps_out_3", "auc_out.Rdata")
save(auc_output, file = save_file)

STAR_in_file <- file.path(VARS_dir, "forceeps_out_3", "STAR_in.smp")
STAR_in <- unlist(auc_output)
write(STAR_in, STAR_in_file, ncolumns=1)


