---
output: 
  stevetemplates::article:
    fig_caption: true
#bibliography: master.bib
biblio-style: apsr
title: "Phenofit calibration comparison"
# thanks: "Replication files are available on the author's Github account (http://github.com/svmiller). **Current version**: `r format(Sys.time(), '%B %d, %Y')`; **Corresponding author**: svmille@clemson.edu."
author:
- name: Victor Van der Meersch
  affiliation: CEFE, CNRS
abstract: "This document provides some insights to compare different CMA-ES calibrations with different presence/absence subsets (*F. sylvatica* with 1000 random presence points and 1000 random absence points)."
# keywords: "pandoc, r markdown, knitr"
date: "`r format(Sys.time(), '%B %d, %Y')`"
#geometry: margin=1cm
fontfamily: mathpazo
fontsize: 11pt
# spacing: double
endnote: no
header-includes:
  - \usepackage{graphicx}
  - \usepackage{float}
  - \floatplacement{figure}{H}
  - \usepackage[width=.6\textwidth, textfont=it, font=small]{caption}
  - \usepackage{nopageno}
  - \setlength{\voffset}{-0.4in}
  - \geometry{top=1in, bottom=-1in, left=1.25in, right=1.25in}

---

```{r setup, include=FALSE}
wd <- 'C:/Users/vandermeersch/Documents/CEFE/thesis/phenofit/calibration_comparison'
source(file.path(wd, "functions", "read_species_file.R"))
source(file.path(wd, "functions", "read_mean_outputvalue.R"))

library(ggplot2)
library(ggthemes)
library(dplyr)
library(AUC)
library(cowplot)
library(ecospat)

knitr::opts_chunk$set(cache=TRUE,
                      message=FALSE, warning=FALSE,
                      fig.path='figs/',
                      cache.path = '_cache/',
                      fig.process = function(x) {
                      x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
                      if (file.rename(x, x2)) x2 else x
                      })

# Way to get lat/lon
climate_folder <- "D:/climate/ERA5-Land/phenofit_format/transformed"
alt_file <- paste0(climate_folder, "/ERA5LAND_", "Altitude.fit")
alt <- fread(alt_file, showProgress=F)
colnames(alt) <- c("lat", "lon", "alt")
alt$lat <- round(alt$lat, 1)
alt$lon <- round(alt$lon, 1)

```

```{r parameters, include=FALSE}

# species presence/absence
load("D:/species/processed/fagus_sylvatica/fagussylvatica_presabs.Rdata")
presence_records <- left_join(alt, fagussylvatica_presabs, by = c('lat', 'lon')) %>% dplyr::select(-c('alt'))

# List of CMAES calibrations 
cal_folder <- 'D:/calibrations/phenofit/fagus_sylvatica/1000pres_1000abs'
sim_folder <- 'D:/simulations/phenofit/backward/fagus_sylvatica'
species_folder <- 'D:/species/processed/fagus_sylvatica/1000pres_1000abs'
cal_list <- c("15-04", "22-04a", "22-04b", "22-04c", "22-04d", "28-04a", "28-04b", "02-05", "03-05", "04-05a")
subset_list <- c("1", "2", "4", "3", "5", "6", "7", "9", "8", "10")

# Bounds
bd_folder <- 'C:/Users/vandermeersch/Dropbox/These_Victor/Phenofit4/species/backward/fagus_sylvatica'
species_lb  <- as.numeric(read_species_file(file.path(bd_folder, 'Fagus_sylvatica_lb.species')))
species_ub <- as.numeric(read_species_file(file.path(bd_folder, 'Fagus_sylvatica_ub.species')))
species_init <- as.numeric(read_species_file(file.path(bd_folder, 'Fagus_sylvatica_init.species')))

# Load values
species_parameters <- lapply(cal_list, function(x){
  cal_folder <- file.path(cal_folder,x)
  species_file <- list.files(path = cal_folder, pattern = "\\.species$", full.names = T)
  species_values <- data.frame(value = read_species_file(species_file)) %>% 
    mutate_all(as.numeric)
  species_values$var <- rownames(species_values)
  species_values$lb <- species_lb
  species_values$ub <- species_ub
  species_values$init <- species_init
  species_values
  })
species_parameters <- do.call(rbind, species_parameters)
species_parameters <- na.omit(species_parameters) #remove fixed parameters (bounds = NA)
```

# 1. Species parameters

## 1.1. Leaf unfolding model


```{r leaf_parameters, echo=FALSE, fig.height = 5, fig.width = 5, fig.align = "center", fig.cap = "Leaf unfolding model parameter values. Y-axis limits are lower and upper bounds used during calibration. Dashed line is initial parameter value.", fig.pos="H"}

data <- species_parameters %>%
  dplyr::filter(grepl("leaf", species_parameters$var))
par_names <- c("t0", "Vb", "d", "e", "Ccrit", "Fcrit")
names(par_names) <- unique(data$var)

data %>%
  ggplot(aes(y = value, x = factor(1))) +
  geom_point(alpha=0.5, col = 'darkred') + 
  geom_violin(fill = 'lightgrey', alpha= 0.1) +
  geom_hline(aes(yintercept = init), linetype = 'dashed', col = 'darkred') +
  facet_wrap("var", scales="free",
             labeller= labeller(var = par_names)) +
  geom_blank(aes(y = lb)) +
  geom_blank(aes(y = ub)) +
  theme_hc() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())


# geom_dotplot(binaxis = 'y', stackdir='center', alpha=0.5, col = 'darkred') can also be an option ?


```

## 1.2. Flowering model

```{r flower_parameters, echo=FALSE, fig.height = 5, fig.width = 5, fig.align = "center", fig.cap = "Flowering model parameter values. Y-axis limits are lower and upper bounds used during calibration. Dashed line is initial parameter value.", fig.pos="H"}

data <- species_parameters %>%
  dplyr::filter(grepl("flower", species_parameters$var))
par_names <- c("t0", "Vb", "d", "e", "Ccrit", "Fcrit")
names(par_names) <- unique(data$var)

data %>%
  ggplot(aes(y = value, x = factor(1))) +
  geom_point(alpha=0.5, col = 'darkred') + 
  geom_violin(fill = 'lightgrey', alpha= 0.1) +
  geom_hline(aes(yintercept = init), linetype = 'dashed', col = 'darkred') +
  facet_wrap("var", scales="free",
             labeller= labeller(var = par_names)) +
  geom_blank(aes(y = lb)) +
  geom_blank(aes(y = ub)) +
  theme_hc() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())



```

## 1.3. Fruit maturation model

```{r fruit_parameters, echo=FALSE, fig.height = 5, fig.width = 5, fig.align = "center", fig.cap = "Fruit maturation model parameter values. Y-axis limits are lower and upper bounds used during calibration. Dashed line is initial parameter value.", fig.pos="H"}

data <- species_parameters %>%
  dplyr::filter(grepl("fruit", species_parameters$var))
par_names <- c("aa", "bb", "Fcrit", "Top", "matmoy", "sigma", "pfe50")
names(par_names) <- unique(data$var)


data %>%
  ggplot(aes(y = value, x = factor(1))) +
  geom_point(alpha=0.5, col = 'darkred') + 
  geom_violin(fill = 'lightgrey', alpha= 0.1) +
  geom_hline(aes(yintercept = init), linetype = 'dashed', col = 'darkred') +
  facet_wrap("var", scales="free",
             labeller= labeller(var = par_names)) +
  geom_blank(aes(y = lb)) +
  geom_blank(aes(y = ub)) +
  theme_hc() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())


```

## 1.4. Leaf senescence model

```{r senes_parameters, echo=FALSE, fig.height = 5, fig.width = 5, fig.align = "center", fig.cap = "Leaf senescence model parameter values. Y-axis limits are lower and upper bounds used during calibration. Dashed line is initial parameter value.", fig.pos="H"}

data <- species_parameters %>%
  dplyr::filter(grepl("senes", species_parameters$var))
par_names <- c("Pb", "Tb", "alpha", "beta", "Scrit", "sigmaSen")
names(par_names) <- unique(data$var)


data %>%
  ggplot(aes(y = value, x = factor(1))) +
  geom_point(alpha=0.5, col = 'darkred') + 
  geom_violin(fill = 'lightgrey', alpha= 0.1) +
  geom_hline(aes(yintercept = init), linetype = 'dashed', col = 'darkred') +
  facet_wrap("var", scales="free",
             labeller= labeller(var = par_names)) +
  geom_blank(aes(y = lb)) +
  geom_blank(aes(y = ub)) +
  theme_hc() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())


```

## 1.5. Frost damage model

```{r frost_parameters, echo=FALSE, fig.height = 6, fig.width = 6, fig.align = "center", fig.cap = "Frost damage model parameter values. Y-axis limits are lower and upper bounds used during calibration. Dashed line is initial parameter value.", fig.pos="H"}

data <- species_parameters %>%
  dplyr::filter(grepl("frost", species_parameters$var))
par_names <- c("FHfrmax1", "FHfrmax2", "FHminfe", "FHminfl", "Te1", "Te2", "FHtfemax", "FHtflmax", "FHpfemax", "FHpflmax", "NL1", "NL2")
names(par_names) <- unique(data$var)


data %>%
  ggplot(aes(y = value, x = factor(1))) +
  geom_point(alpha=0.5, col = 'darkred') + 
  geom_violin(fill = 'lightgrey', alpha= 0.1) +
  geom_hline(aes(yintercept = init), linetype = 'dashed', col = 'darkred') +
  facet_wrap("var", scales="free",
             labeller= labeller(var = par_names)) +
  geom_blank(aes(y = lb)) +
  geom_blank(aes(y = ub)) +
  theme_hc() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())


```

## 1.6. Drought damage model

```{r drought_parameters, echo=FALSE, fig.height = 5, fig.width = 5, fig.align = "center", fig.cap = "Drought damage model parameter values. Y-axis limits are lower and upper bounds used during calibration. Dashed line is initial parameter value.", fig.pos="H"}

data <- species_parameters %>%
  dplyr::filter(grepl("drought", species_parameters$var))
par_names <- c("ppextremelow", "pplow", "pphigh", "ppextremehigh")
names(par_names) <- unique(data$var)


data %>%
  ggplot(aes(y = value, x = factor(1))) +
  geom_point(alpha=0.5, col = 'darkred') + 
  geom_violin(fill = 'lightgrey', alpha= 0.1) +
  geom_hline(aes(yintercept = init), linetype = 'dashed', col = 'darkred') +
  facet_wrap("var", scales="free",
             labeller= labeller(var = par_names)) +
  geom_blank(aes(y = lb)) +
  geom_blank(aes(y = ub)) +
  theme_hc() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())


```


# 2. Model outputs

## 2.1. Discrimination metrics

```{r auc, echo=FALSE, fig.height = 5, fig.width = 5, fig.align = "center", fig.cap = "AUC on (a) calibration points and (b) every presence/absence points. ", fig.pos="H"}

auc_data <- data.frame()

for(i in 1:length(subset_list)){
  
  # Load AUC on calibration_points
  cal_dir <- file.path(cal_folder, cal_list[i])
  cmaes_fit <- list.files(path = cal_dir, pattern = "\\.Rdata$", full.names = T)
  load(cmaes_fit)
  auc_cal <- 1-round(cmaes_fit[[1]][["value"]], 3)
  
  auc_data[i, 'cal'] <- auc_cal
  
  # Load AUC on every pres/abs points
  sim_dir <- file.path(sim_folder, cal_list[i])
  fitness_presabs <- read_mean_outputvalue(sim_dir, "Fitness", points = fagussylvatica_presabs)
  auc_presabs <- round(auc(roc(fitness_presabs, as.factor(fagussylvatica_presabs$pres))),3)
  
  auc_data[i, 'presabs'] <- auc_presabs
  
  
}

cal_plot <- auc_data %>%
  ggplot(aes(y = cal, x = factor(1))) +
  geom_point(alpha=0.5, col = 'darkred', position = position_dodge2(w = 0.25)) + 
  geom_violin(fill = 'lightgrey', alpha= 0.1) +
  geom_blank(aes(y = 0.875)) +
  geom_blank(aes(y = 0.925)) +
  theme_hc() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())


presabs_plot <- auc_data %>%
  ggplot(aes(y = presabs, x = factor(1))) +
  geom_point(alpha=0.5, col = 'darkred', position = position_dodge2(w = 0.25)) +
  geom_violin(fill = 'lightgrey', alpha= 0.1) +
  geom_blank(aes(y = 0.875)) +
  geom_blank(aes(y = 0.925)) +
  theme_hc() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())


plot_grid(cal_plot, presabs_plot, labels=c("(a)", "(b)"), ncol = 2, nrow = 1,
          hjust = 0, vjust = 1)


```

## 2.2. Reliability metrics

```{r boyce, echo=FALSE, fig.height = 5, fig.width = 5, fig.align = "center", fig.cap = "Boyce index on every presence points, with (a) Spearman correlation, (b) Pearson correlation and (c) Kendall correlation.", fig.pos="H"}

boyce_data <- data.frame()

for(i in 1:length(subset_list)){
  
  # Load fitness
  sim_dir <- file.path(sim_folder, cal_list[i])
  fitness <- read_mean_outputvalue(sim_dir, "Fitness")
  
  fitness_obs <- fitness[which(presence_records$pres == 1)]
  
  
  boyce_list <- ecospat.boyce(fit = fitness, obs = fitness_obs, nclass=0, window.w="default", res=100, PEplot = F, rm.duplicate = F,  method = 'spearman' )
  boyce_data[i, "spearman"] <- boyce_list$cor
  boyce_list <- ecospat.boyce(fit = fitness, obs = fitness_obs, nclass=0, window.w="default", res=100, PEplot = F, rm.duplicate = F,  method = 'pearson' )
  boyce_data[i,"pearson"] <- boyce_list$cor
  boyce_list <- ecospat.boyce(fit = fitness, obs = fitness_obs, nclass=0, window.w="default", res=100, PEplot = F, rm.duplicate = F,  method = 'kendall' )
  boyce_data[i, "kendall"] <- boyce_list$cor
  
  
}

bi_sp_plot <- boyce_data %>%
  ggplot(aes(y = spearman, x = factor(1))) +
  geom_point(alpha=0.5, col = 'darkred') + 
  geom_violin(fill = 'lightgrey', alpha= 0.1) +
  geom_blank(aes(y = 0.67)) +
  geom_blank(aes(y = 1)) +
  theme_hc() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())

bi_pr_plot <- boyce_data %>%
  ggplot(aes(y = pearson, x = factor(1))) +
  geom_point(alpha=0.5, col = 'darkred') + 
  geom_violin(fill = 'lightgrey', alpha= 0.1) +
  geom_blank(aes(y = 0.67)) +
  geom_blank(aes(y = 1)) +
  theme_hc() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())

bi_kd_plot <- boyce_data %>%
  ggplot(aes(y = kendall, x = factor(1))) +
  geom_point(alpha=0.5, col = 'darkred') + 
  geom_violin(fill = 'lightgrey', alpha= 0.1) +
  geom_blank(aes(y = 0.67)) +
  geom_blank(aes(y = 1)) +
  theme_hc() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())


plot_grid(bi_sp_plot, bi_pr_plot, bi_kd_plot, labels=c("(a)", "(b)", "(c)"), ncol = 3, nrow = 1,
          hjust = 0, vjust = 1)


```

## 2.3. Species distribution

```{r species_distribution, echo=FALSE, fig.height = 5, fig.width = 5, fig.align = "center", fig.cap = "Number of consensual presence predicted by models.", fig.pos="H"}

presabs_data <- as.data.frame(cbind(alt$lat, alt$lon))

for(i in 1:length(subset_list)){
  
  # Load fitness
  sim_dir <- file.path(sim_folder, cal_list[i])
  fitness <- read_mean_outputvalue(sim_dir, "Fitness")
  
  # Load fitness only on pres/abs points
  fitness_presabs <- read_mean_outputvalue(sim_dir, "Fitness", points = fagussylvatica_presabs)
  
  # Best threshold maximizing Youden index
  youden_index <- sensitivity(fitness_presabs, as.factor(fagussylvatica_presabs$pres))$measure +
    specificity(fitness_presabs, as.factor(fagussylvatica_presabs$pres))$measure -1
  thresholds <- roc(fitness_presabs, as.factor(fagussylvatica_presabs$pres))$cutoffs
  best_threshold <- thresholds[which(youden_index == max(youden_index))]
  
  # Presence/absence
  data_presence <- data.frame(fitness = t(fitness))  
  data_presence[data_presence$fitness < best_threshold, 'presence'] <- 0  
  data_presence[data_presence$fitness >= best_threshold, 'presence'] <- 1
  
  presabs_data[,2+i] <- data_presence$presence
  
}

names(presabs_data) <- c("lat", "lon", paste0("sim",as.character( 1:length(subset_list))))

# Consensus 
presabs_data$cons <- rowSums(presabs_data[,3:(2+length(subset_list))])

ggplot(data=presabs_data, aes(x = lon, y = lat)) + 
  geom_tile(aes(fill = cons), color = NA) +
  theme_void() +
  labs(fill = "") +
  ylab("") +
  xlab("") +
  scale_fill_gradient(low = "#EBEBD3", high = "#488B49")

```


<!--
# References
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\vspace*{-0.2in}
\noindent
-->
