---
title: "Contrasted hindcast performances demonstrate the need for more realistic species distribution models"
subtitle: "Figures for manuscript and supplementary figures"
author: "V. Van der Meersch et al."
geometry: "left=1cm,right=1cm,top=1cm,bottom=1cm"
output: 
  pdf_document:
    keep_tex: true
header-includes:
  \pagenumbering{gobble}
  \usepackage{float}
  \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
wd <- "C:/Users/vandermeersch/Documents/CEFE/projects/past_robustness"

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, 
                      results='hide', fig.path= paste0(wd, "/manuscript/figs/files/"), fig.pos = 'H')
library(chunkhooks)
hook_figure_unit("mm")

source(file.path(wd, "manuscript", "processing", "setup.R"))
```

# Main

```{r climatic_dissimilarity, fig.height = 60, fig.width = 150, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Climatic dissimilarity.", eval = T}
 source(file.path(wd, "manuscript", "figs", "fig1", "main.R"))
fig1_main
```

\newpage

```{r process_model_outputs, include = F, eval = F}
source(file.path(wd, "manuscript", "processing", "model_simulations.R"))
source(file.path(wd, "manuscript", "processing", "model_transferability.R"))

# model_performance_relchg <- readRDS("C:/Users/vandermeersch/Documents/CEFE/projects/past_robustness/manuscript/processing/output/model_performance_relchg.rds")
# model_performance_withmig<- readRDS( "C:/Users/vandermeersch/Documents/CEFE/projects/past_robustness/manuscript/processing/output/model_performance_withmig.rds")
model_performance_withmig$clim_hpv_sorensen.mean <- 1-model_performance_withmig$clim_hpv_sorensen.mean # dissimilarity
```

```{r quercus_deciduous_simulations, fig.height = 240, fig.width = 150, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Quercus deciduous simulations.", eval = F}

source(file.path(wd, "manuscript", "figs", "fig2", "main.R")) 
fig2_main

```

\newpage

```{r past_performance, fig.height = 120, fig.width = 190, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Beta regression and boxplots.", eval = F}

source(file.path(wd, "manuscript", "processing", "ordered_beta_regression.R"))

source(file.path(wd, "manuscript", "figs", "fig3", "beta_regression.R"))
source(file.path(wd, "manuscript", "figs", "fig3", "boxplot_performance.R"))
source(file.path(wd, "manuscript", "figs", "fig3", "boxplot_variance.R"))
source(file.path(wd, "manuscript", "figs", "fig3", "boxplot_transferability.R"))
source(file.path(wd, "manuscript", "figs", "fig3", "main.R"))
fig3_main

```

\newpage

# Supplementary data

\renewcommand{\thefigure}{A.\arabic{figure}}
\setcounter{figure}{0}

```{r climate_overview, fig.height = 105, fig.width = 180, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Past climate overview.", eval = F}
source(file.path(wd, "manuscript", "figs", "suppmat", "figA1.R"))
figA1_main
```

```{r climatic_dissimilarity_pergcm, fig.height = 70, fig.width = 170, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Climatic dissimilarity.", eval = F}
source(file.path(wd, "manuscript", "figs", "suppmat", "figA2.R"))
figA2_main
```

```{r climatic_dissimilarity_and_distance, fig.height = 90, fig.width = 200, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Climatic dissimilarity vs climatic distance.", eval = T}
source(file.path(wd, "manuscript", "figs", "suppmat", "figA3.R"))
figA3_main
```


```{r migration_process, fig.height = 100, fig.width = 90, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Illustration of Q. deciduous migration process. PHENOFIT (fitted) from 12000BP.", eval = F}
source(file.path(wd, "manuscript", "figs", "suppmat", "figA4.R"))
figA4_main
```

```{r fagus_simulations, fig.height = 240, fig.width = 150, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Fagus simulations.", eval = F}
source(file.path(wd, "manuscript", "figs", "suppmat", "figA5.R")) 
figA5_main
```

```{r abies_simulations, fig.height = 240, fig.width = 150, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Abies simulations.", eval = F}
source(file.path(wd, "manuscript", "figs", "suppmat", "figA6.R")) 
figA6_main

```

```{r quercusevergreen_simulations, fig.height = 240, fig.width = 150, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Quercus evergreen simulations.", eval = F}
source(file.path(wd, "manuscript", "figs", "suppmat", "figA7.R")) 
figA7_main
```

```{r performance_perspecies, fig.height = 130, fig.width = 150, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Performance per species per type of model.", eval = F}
source(file.path(wd, "manuscript", "figs", "suppmat", "figA8.R")) 
figA8_main
```

```{r performance_perspecies_permodel, fig.height = 130, fig.width = 150, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Performance per species per model.", eval = F}
source(file.path(wd, "manuscript", "figs", "suppmat", "figA9.R")) 
figA9_main
```

```{r current_performance, fig.height = 85, fig.width = 110, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Performance against time.", eval = F}

source(file.path(wd, "manuscript", "figs", "suppmat", "figA14.R")) 
figA14_main
```

```{r performance_time, fig.height = 85, fig.width = 110, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Performance against time.", eval = F}

source(file.path(wd, "manuscript", "processing", "suppmat", "linear_plateau_regression.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figA13.R")) 
figA13_main
```

```{r performance_perspeciesmigration, fig.height = 100, fig.width = 195, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Performance per species per type of model.", eval = F}
source(file.path(wd, "manuscript", "figs", "suppmat", "figA12.R")) 
figA12_main
```

```{r past_performance_womigration, fig.height = 120, fig.width = 190, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Beta regression and boxplots. Without migration.", eval = F}

# source(file.path(wd, "manuscript", "processing", "suppmat", "model_transferability_womigration.R"))

source(file.path(wd, "manuscript", "processing", "suppmat", "ordered_beta_regression_womigration.R"))

source(file.path(wd, "manuscript", "figs", "suppmat", "figA9", "beta_regression.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figA9", "boxplot_performance.R"))
# source(file.path(wd, "manuscript", "figs", "suppmat", "figA9", "boxplot_variance.R"))
# source(file.path(wd, "manuscript", "figs", "suppmat", "figA9", "boxplot_transferability.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figA9", "main.R"))



```


```{r past_performance_from12000, fig.height = 120, fig.width = 190, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Beta regression and boxplots", eval = F}

source(file.path(wd, "manuscript", "processing", "suppmat", "model_simulations_from11750.R"))
# source(file.path(wd, "manuscript", "processing", "model_transferability.R"))

model_performance_withmig$clim_hpv_sorensen.mean <- 1-model_performance_withmig$clim_hpv_sorensen.mean # dissimilarity

source(file.path(wd, "manuscript", "processing", "suppmat", "ordered_beta_regression_from11750.R"))

source(file.path(wd, "manuscript", "figs", "suppmat", "figA10", "beta_regression.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figA10", "boxplot_performance.R"))
# source(file.path(wd, "manuscript", "figs", "suppmat", "figA10", "boxplot_variance.R"))
# source(file.path(wd, "manuscript", "figs", "suppmat", "figA10", "boxplot_transferability.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figA10", "main.R"))




```

```{r past_performance_differentstarts, fig.height = 240, fig.width = 180, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Beta regression and boxplots", eval = F}

source(file.path(wd, "manuscript", "processing", "suppmat", "model_simulations_from12000.R"))
# source(file.path(wd, "manuscript", "processing", "model_transferability.R"))

model_performance_withmig$clim_hpv_sorensen.mean <- 1-model_performance_withmig$clim_hpv_sorensen.mean # dissimilarity

source(file.path(wd, "manuscript", "processing", "suppmat", "ordered_beta_regression_from12000.R"))

source(file.path(wd, "manuscript", "figs", "suppmat", "figA11", "beta_regression.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figA11", "boxplot_performance.R"))
# source(file.path(wd, "manuscript", "figs", "suppmat", "figA11", "boxplot_variance.R"))
# source(file.path(wd, "manuscript", "figs", "suppmat", "figA11", "boxplot_transferability.R"))
source(file.path(wd, "manuscript", "figs", "suppmat", "figA11", "main.R"))

plot_grid(plot_grid(NULL, figA13_main, NULL,
                    labels = c("","a","") , 
                    ncol = 3,
                    rel_widths = c(0.2,0.6,0.2),
                    label_fontfamily = "Helvetica Narrow", label_size = 11), 
          figA9_main, figA10_main, figA11_main, get_legend(ordbetareg_plot),
                            ncol = 1, rel_heights = c(0.5, 0.5, 0.5, 0.5, 0.1))



```


```{r historical_perf, fig.height = 70, fig.width = 160, dev=c('cairo_pdf'), dpi = 600, fig.cap = "Historical_perf.", eval = F}
source(file.path(wd, "manuscript", "figs", "suppmat", "figA14.R"))
figA14_main
```

```{r hypervolume_representation, fig.height = 80, fig.width = 160, dev=c('ragg_png'), dpi = 400, fig.cap = "Historical_perf.", eval = F}
source(file.path(wd, "manuscript", "figs", "suppmat", "figA15.R"))
figA15_main
```