###############################################################
# Script to perform a Variogram Analysis of Response Surfaces #
###############################################################

## Castanea model

# use the STAR_out.smp file generated by VARS Toolbox (MatLab)

# Setup
wd <- "/scratch/vvandermeersch/castanea"
source(file.path(wd, "sensitivity_analysis", "setup.R"))
source(file.path(wd, "functions", "read_auc.R"))

# Read parameter matrix
#VARS_dir <- "/scratch/vvandermeersch/castanea/sensitivity_analysis/VARS_files"
#parameter_matrix_file <- file.path(VARS_dir, "STAR_out.smp")
#parameter_matrix <- fread(parameter_matrix_file, header=F)

# Load presence/absence (to compute AUC)
load("/scratch/vvandermeersch/data/species/fagsyl/fagussylvatica_occ_rs.Rdata")
library(raster)
species_occurrence <- as.data.frame(fagussylvatica_occ_rs, xy=T)
names(species_occurrence)[1:2] <- c("lon", "lat")
species_occurrence$lat <- round(species_occurrence$lat, 1)
species_occurrence$lon <- round(species_occurrence$lon, 1)
species_occurrence <- inner_join(alt_subset, species_occurrence, by = c("lat", "lon"))
species_occurrence$pres <- 0
species_occurrence[species_occurrence$nb_src>0, "pres"] <- 1
Yobs <- species_occurrence
obs <- as.factor(Yobs$pres)

# Run model
output_path <- file.path(wd, "sensitivity_analysis", "test") 
parameters_fixed <- c("Lignroots", "LIGNrl", "LIGNll", "LIGNfb", "LIGNcb", "LIGNcr", "NSS", "potToWood", "ratioG",
                      "CoefLAI3", "RauwPIR", "RauwPAR", "RaufPIR", "TaufPIR", "RaufPAR", "TaufPAR",
                      "emsf", "propec", "CapSoilleaf", "EaVJ", "ETT", "JMT", "teta", "TBASEC", 
                      "NSTART3", "T1rec", "decidue", "cohorLeaves", "BSSminCrit", "rateOfSeed", "rateOfSeedJourne", "seedMass_mg",
                      "seedMass_mu")
logfile <- file.path(wd, "sensitivity_analysis", "log", "vars.log")

# test matrix
#p <- parameters$init[!(names(parameters$init) %in% parameters$fixed)]
load("/scratch/vvandermeersch/castanea/sensitivity_analysis/p.Rdata")
mat <- matrix(c(p,p), nrow = 2, byrow = T)

#run_model_from_mat(mat, ncores = 2, log = logfile)
# 2 sim for 3 years on 990 pts, on 2 cores => 1162 sec

# Read AUC
var <- "BiomassOfReserves"

auc_output <- c()
nind <- nrow(mat)
npack <- 100
inds <- split(1:nind, cut(seq_along(1:nind), npack, labels = FALSE))
system.time(for(i in 1:npack){
  auc_i <- read_auc(inds[[i]], ncores = 40)
  auc_output <- c(auc_output, auc_i)
})